language: node_js

node_js:
  - "4.6" 

python:
  - "2.7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages
        - g++-4.8

install:
  - pip install flake8

script:
  - "npm run build"
  - "npm run travis-lint"
  - flake8 
